name: Python Formatting, Linting, and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0

      - name: Install poetry
        run: |
          python -m pip install poetry==1.1.11
    
      - name: Configure poetry
        run: |
          python -m poetry config virtualenvs.in-project true
    
      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}
    
      - name: Install dependencies
        run: |
          python -m poetry install

      - name: Format code with Black
        run: black .

      - name: Sort imports with isort
        run: isort .

      - name: Lint code with Ruff
        run: ruff .

      - name: Run tests with pytest
        run: pytest
